name: Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: install & deploy
        run: |
          npm install
          npm run build
          npm run deploy
        with:
          node-version: 16
